#!/bin/bash

begin

case $1 in
	start)
		/usr/local/sbin/vs-snapshot --on
	;;
	stop)
		/usr/local/sbin/vs-snapshot --off
	;;
	status)
		/usr/local/sbin/vs-snapshot
	;;
	*)
		echo "Usage: /etc/init.d/snapshot start|stop|status"
	;;
esac

success
	